[features]
seeds = false
skip-lint = false

[programs.devnet]
ikkii_escrow = "7rP4rHKBqnYGB2UgpeRtd9f3FZ1PHwfc4iPVhWRv9UP4"
ikkii_escrow_v2 = "4T3bc2eimNKACT9FxTJaySC5jzqaBLct8Zo4BDjprnN2"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/RealAuthority.json"

[scripts]
test = "NODE_OPTIONS='--no-warnings' npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
